language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "pypy"
  - "pypy3"

env:
  PYTHONPATH=../

# command to install dependencies
install: "pip install -r requirements_dev.txt"

# script run flake8
before_script: flake8 .

# run tests
script: py.test
